spring:
  datasource:
    name: sc-library-reservations
    platform: h2
    url: jdbc:h2:mem:sc-library-reservations;DATABASE_TO_UPPER=false;IGNORECASE=true;
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      path: /db-console

server:
  address: localhost
  port: 8081

sc:
  book-service-url: http://localhost:8080/api/books/
